
CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(16) BINARY NOT NULL UNIQUE COMMENT '用户名, 主键',
  nickname VARCHAR(16) BINARY DEFAULT NULL COMMENT '昵称',
  password VARCHAR(64) BINARY NOT NULL COMMENT '用户密码,加密',
  email VARCHAR(50) BINARY NOT NULL COMMENT '用户邮箱',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '用户头像地址',
  gender BOOL DEFAULT 0 COMMENT '性别，默认男',
  city VARCHAR(16) DEFAULT NULL COMMENT '所在城市',
  summary TEXT DEFAULT NULL COMMENT '个人简介',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp COMMENT '最后一次更新时间',
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS Article (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  title VARCHAR(32) BINARY UNIQUE NOT NULL COMMENT '标题',
  content TEXT NOT NULL COMMENT '文章内容',
  views INT UNSIGNED DEFAULT 0 COMMENT '文章阅读量',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp COMMENT '最后一次更新时间',
  PRIMARY KEY (id),
  INDEX title_index(title)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS Label (
  label VARCHAR(16) BINARY UNIQUE NOT NULL COMMENT '具体标签',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  PRIMARY KEY (label)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS ArticleLabel(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  article_id SMALLINT UNSIGNED NOT NULL COMMENT '文章表的id',
  label VARCHAR(16) BINARY NOT NULL COMMENT '标签',
  PRIMARY KEY (id),
  UNIQUE KEY (article_id, label),
  CONSTRAINT article_fk FOREIGN KEY(article_id) REFERENCES Article(id) ON DELETE CASCADE on UPDATE CASCADE,
  CONSTRAINT label_fk FOREIGN KEY (label) REFERENCES Label(label) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS Comment(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  article_id INT NOT NULL COMMENT '评论所属的文章',
  content TEXT DEFAULT NULL COMMENT '评论的正文',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  PRIMARY KEY (id),
  INDEX article_id_index(article_id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;