version: '3.7'

services:
  docs:
    container_name: blog-docs
    restart: always
    ports:
      - 8889:80
    build:
      context: ./doc
      dockerfile: ../script/Dockerfile-Docs

  nginx:
    container_name: blog-nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./script/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/blogback:/var/log/nginx

  backend:
    container_name: blog-backend
    restart: always
    image: jianjiago/blogback:dev
    links:
      - db
    ports:
      - "8888"
    volumes:
      - /var/log/blogback:/var/log/blogback
  db:
    container_name: blog-db
    restart: always
    image: mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: edgar
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306
    volumes:
      - ./script/blog.sql:/docker-entrypoint-initdb.d/blog.sql
#      - ~/docker/mysql/data:/var/lib/mysql