TRUNCATE TABLE User;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE ArticleLabel;
TRUNCATE TABLE Article;
TRUNCATE TABLE Label;
SET FOREIGN_KEY_CHECKS = 1;
TRUNCATE TABLE Comment;

DROP TABLE User;
DROP TABLE ArticleLabel;
DROP TABLE Article;
DROP TABLE Label;
DROP TABLE Comment;